public class fundRaiser {
    public string vmgID;
    public string ForeName;
    public string SurName;
    
    public String getvmgID(){return vmgID;}
    public String getForeName(){return ForeName;}
    public String getSurName(){return SurName;}
   
    public void setvmgID(String str)
    {
        this.vmgID = str;
    }
    public void setForeName(String str)
    {
        this.ForeName = str;
    }
    public void setSurName(String str)
    {
        this.SurName = str;
    }
}